### ISSUE TITLE
Fatal error: Cannot redeclare class User

### ISSUE THREAD

**Issue by Keo777** [daveismyname/simple-blog-part-6-pagination#4]
Fatal error: Cannot redeclare class User in /classes/class.user.php on line 53

**Comment by dcblogdev** [comment]
what version of php are you running? I've downloaded the files from this repo and unable to reproduce this error.

**Comment by Keo777** [comment]
5.4.44

What version are you running?

**Comment by dcblogdev** [comment]
Tried it on 7 and just now on 5.4.45 it's also running my server which is 5.6.

Still trying to recreate the problem, worse case is to do a require for each class in the config file instead of using the autoload functions.

**Comment by Keo777** [comment]
Nevermind, it seems it was due to the fact that I had already installed the blog (the one in part 1) in a different folder with a different database. Didn't realize that would interfere.

But now I have an error when trying to open an article. Gives a 404 error. Guess I'll open a separate thread on that one.
