### ISSUE TITLE
Fatal error: Uncaught PDOException

### ISSUE THREAD

**Issue by dyanakiev** [daveismyname/simple-blog-part-6-pagination#5]
Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or
access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP
BY clause and contains nonaggregated column
'xxx.blog_posts_seo.postDate' which is not functionally dependent on
columns in GROUP BY clause; this is incompatible with
sql_mode=only_full_group_by in
/xxx/public/blog/
sidebar.php:30 Stack trace: #0
/xxx/public/blog/
sidebar.php(30): PDO->query('SELECT Month(po...') #1
/xxxx/public/blog/
index.php(63): require('xxx') #2 {main} thrown in
/xxx/public/blog/
sidebar.php on line 30

**Comment by systemroot** [comment]
what os/webserver are you using for it?!

**Comment by dcblogdev** [comment]
you must be used MariaDB it's more strict, that error means the group by the information needs to be in the select criteria too.
