### ISSUE TITLE
user still logged in after deleting his account.

### ISSUE THREAD

**Issue by systemroot** [daveismyname/simple-blog-part-6-pagination#7]
create one account, then login in another browser,

then delete it, go on that browser when you logged in and do whatever you want you won't get logout even if account doesn't exist!

Just i want to report this, and as for now i wasn't able to find a solution!

**Comment by daveismyname** [comment]
this was a super simple implementation, lots of things can be imported for this having a check for an active account for the logged in user then delete the session.
