### ISSUE TITLE
you should remove tinymce!

### ISSUE THREAD

**Issue by systemroot** [daveismyname/simple-blog-part-6-pagination#9]
Hi.

You should remove tinymce from text editor.. shomehow it's bad for posts seo.
when we edit post desc with tinymce editor the text will be add in database with `"div, p, b"` and others stuff. so when you will try to add 
```php
<meta property="og:description" content="<?php echo $row['postDesc'];?>" />
```
in your blog, it will not work. (you can check by yourself https://developers.facebook.com/tools/debug/sharing/)

This problem is solved in my case i just was thinking to report it here. so you can close after you read this.

**Comment by daveismyname** [comment]
you don't add meta tags in the post content, for this purpose add the meta tags to the single post page instead.
